// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://memoyavcgakwyytreplr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbW95YXZjZ2Frd3l5dHJlcGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIyMTUsImV4cCI6MjA2NTQ4ODIxNX0.Q0agWR4nmvUUyXDhRC5vqMBRImFrsFNAqfI4yq8KlRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);